### ISSUE TITLE
[기획] 팀프로젝트 주제 선정

### ISSUE THREAD

**Issue by corby9967** [HaHaHoHo-2023OSSL/Miniproject_HaHoVoca#5]
팀프로젝트 주제에 대해서 아이디어가 있다면 자유롭게 의견 제시해주세요!

**Comment by corby9967** [comment]
저는 개인적으로 <말해보카> 앱을 1년 정도 사용해보면서, 자체적으로 영단어 퀴즈 프로그램을 만들어보고 싶다는 생각이 들었습니다!
프로그램의 목적으로는 영단어 암기를 조금 더 재미있게 접근하기 위함입니다.
기능으로서는 기본적인 CRUD 기능과 파일저장/조회 기능 외에,
* 리스트에 있는 영단어로 퀴즈를 제공하고 맞추면 점수를 부여하는 기능
* 총 점수로 랭크를 매기는 기능
등을 생각해보았습니다.

감사합니다!

**Comment by redm27** [comment]
저는 이번 학기 기숙사에 거주하면서, 기숙사생들을 위한 관리 프로그램을 만들면 좋겠다는 생각을 하게 되었습니다.
프로그램의 목적으로는 더욱 간편한 기숙사생들을 위한 프로그램을 만드는 것입니다.
들어갈 기능들은 다음과도 같습니다.

1.  기초적인 학생 정보 관리
2.  학생 심야 시간 외출 외박 관리
3.  세탁 카드 관리 시스템 (입금 및 잔액 확인)
4.  벌점 관리 시스템 (벌점 확인 및 관리자 모드로 벌점 추가 기능 구현)

감사합니다!

**Comment by redm27** [comment]
그러면 저희의 프로젝트 주제는 영어 단어장 암기 및 퀴즈 프로그램을 구현하는 것으로 결정하겠습니다. 감사합니다.
