### ISSUE TITLE
[기획] 구조체 관련 issue

### ISSUE THREAD

**Issue by corby9967** [HaHaHoHo-2023OSSL/Miniproject_HaHoVoca#6]
구조체를 어떻게 구현하면 좋을까요? 회원 정보와 영단어 정보를 합칠까요? 아니면 서로 다른 구조체로 만들까요?

**Comment by redm27** [comment]
하나로 합치는 경우 2차원 배열을 사용하거나,
혹은 먼저 정보를 입력 받아 임시 변수 temp에 저장한 후 새로운 단어를 넣을 때 자동으로 temp의 값으로 정보가 들어가도록 설정하는 방법도 있습니다.

하지만 두 번째 방법의 경우 회원 정보가 정해진 것만 있는 것이 아닌 변수가 있는 경우 애매해진다는 단점이 있습니다.

**Comment by corby9967** [comment]
```c
typedef struct{
    char ID[20];
    char word[10][10];
    char meaning[10][10];
    int score;
} User;
```

저는 이렇게 User라는 하나의 구조체에 ID와 단어 리스트를 함께 구현해보았습니다. 회원마다 고유한 PW 데이터도 포함하여 로그인 기능을 넣어도 좋을 것 같습니다!

**Comment by corby9967** [comment]
최종 결정된 구조체는 Voca 와 User 구조체로, 총 두가지 입니다.
main 함수에서는 User 구조체 타입으로 변수를 선언하여, 각 User에 해당하는 Voca 구조체에 접근하는 로직입니다. 

```c
typedef struct{
    char word[10];
    char meaning[10];
} Voca;

typedef struct{
    int id;
    int index;
    Voca *voca[50];
    char *filename;
} User;
```
