### ISSUE TITLE
[기획] README 파일 수정 시 markdown 문법 issue

### ISSUE THREAD

**Issue by corby9967** [HaHaHoHo-2023OSSL/Miniproject_HaHoVoca#8]
<img width="1010" alt="스크린샷 2023-05-08 오전 12 18 11" src="https://user-images.githubusercontent.com/127426156/236686438-ac135eb6-35d0-4bc5-851c-a8a0b378217e.png">

여기서 ** 두개로 묶어서 Bold체로 만들려고 했는데 적용이 되질 않네요? 어떻게 하면 해결될까요?

**Comment by redm27** [comment]
<div align=left>
</div>

이 사이에 팀원 소개 부분 전체가 들어있었고
팀원 소개 부분을 </div> 밑으로 빼니 bold가 적용이 되었습니다.

**Comment by redm27** [comment]
좋습니다!! html문법과 mark다운 문법을 고려해가며 작성하도록 합시다!!
